In [2]:
# -*- coding: utf-8 -*- 

import tensorflow as tf

'''
이번에는 Matrix를 생성해보겠다.
뭐 Matrix라 해서 그렇게 어려운 것은 없다.
'''

single_matrix = tf.zeros([1,])
double_matrix = tf.zeros([2,])
triple_matrix = tf.zeros([3,]) # 제로 매트릭스를 만들 때는 이런식으로 생성한다.

with tf.Session() as sess:
    print (sess.run(single_matrix))
    print (sess.run(double_matrix))
    print (sess.run(triple_matrix))

[ 0.]
[ 0.  0.]
[ 0.  0.  0.]


In [4]:
# -*- coding: utf-8 -*- 

import tensorflow as tf

'''
음, 이번에는 random_uniform을 이용해보자.
random_uniform은 균등분포에서 아무 값이나 무작위로 뽑아오는 함수다.
'''

# Parameter: 매트릭스 크기, 시작 값, 끝 값
m1 = tf.random_uniform([1], -1,1)
m2 = tf.random_uniform([2,2], 0,1)
m3 = tf.random_uniform([3,3], 1,2)

with tf.Session() as sess:
    print (sess.run(m1))
    print (sess.run(m2))
    print (sess.run(m3))

[-0.99993992]
[[ 0.55375862  0.9614284 ]
 [ 0.71377265  0.31454241]]
[[ 1.29193044  1.73844147  1.69921875]
 [ 1.15893734  1.21749699  1.25023103]
 [ 1.03456771  1.92210531  1.22101986]]


In [5]:
# -*- coding: utf-8 -*- 

import tensorflow as tf

'''
constant를 사용해서 한 번 구현해보자.
'''

m1 = tf.constant([[5,4]]) # [1, 2] Matrix
m2 = tf.constant([[3],[7]]) # [2, 1] Matrix

mul = tf.matmul(m1, m2) # 곱해랏,,

with tf.Session() as sess:
    print (sess.run(m1))
    print (sess.run(m2))
    print (sess.run(mul))

[[5 4]]
[[3]
 [7]]
[[43]]
